#!/usr/bin/with-contenv sh
NET_NAME="$(ls /etc/netclient | grep netconfig- | cut -c 11-)"
while :			# This is the same as "while true".
do
        netclient checkin -n "${NET_NAME}"
        sleep 60
done
